name = "fnb-caffe-container"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "."

[build]
command = "npm run build"

[[build.processing.rules]]
type = "JavaScriptModule"
globs = ["**/*.js"]
